---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Lama"
subtitle: "App dashboard"
logo: false
# icon: "fas fa-skull-crossbones" Optional icon

header: true

# Optional theme customization
theme: sui
colors:
  light:
    highlight-primary: transparent
    highlight-secondary: transparent
    highlight-hover: "#4a4a4a"
    text-subtitle: "#424242"
  dark:
    background: "#2B2C56"
    highlight-primary: transparent
    highlight-secondary: transparent
    highlight-hover: "#200b35"
    text-subtitle: "#6375e8"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Reference"
    icon: "fas fa-book"
    items:
      - name: "WriteFreely"
        logo: "assets/tools/writefreely.png"
        subtitle: "Writing space on the web"
        tag: "app"
        url: "https://write.adrianlam.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Ghost"
        logo: "assets/tools/ghost.png"
        subtitle: "CMS blogging software"
        tag: "app"
        url: "https://blog.adrianlam.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "BookStack"
        logo: "assets/tools/bookstack.png"
        subtitle: "Platform for organising and storing information"
        tag: "app"
        url: "https://wiki.adrianlam.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "FreshRSS"
        logo: "assets/tools/freshrss.png"
        subtitle: "RSS feed aggregator"
        tag: "app"
        url: "https://freshrss.adrianlam.com/"
        target: "_blank" # optional html a tag target attribute
